Printing page
korolovdmitriy/6th-team-project pull request #7
Opened 2021-08-14 11:11 UTC by dmitruz

подключаю шрифты

2021-08-14 13:47 UTC, korolovdmitriy submitted a review, later dismissed

2021-08-14 14:20 UTC, korolovdmitriy requested changes
удали скрипт

2021-08-15 14:49 UTC, dmitruz commented
У меня почему то не видно нашей папки с проектом в моих репозиториях. Я
туда только по сылке могу зайти

сб, 14 авг. 2021 г. в 17:21, Dmitriy Korolov ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> удали скрипт
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/korolovdmitriy/6th-team-project/pull/7#pullrequestreview-730098020>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALBUZWW76QDQ2XF2JM2MO23T4Z3U5ANCNFSM5CE7XBYA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-16 06:16 UTC, korolovdmitriy approved these changes

2021-08-16 06:57 UTC, korolovdmitriy commented
посмотри сколько конфликтов, не могу одобрить(

2021-08-19 11:11 UTC, closed without merging